(function(root){
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
const policies=[{name:'Invest in public hospitals',cost:12,approval:4,economy:1},{name:'Small business tax relief',cost:9,approval:2,economy:4},{name:'Build affordable housing',cost:14,approval:5,economy:2},{name:'Strengthen public integrity',cost:5,approval:3,economy:0},{name:'Expand clean energy',cost:11,approval:3,economy:3},{name:'Reduce public expenditure',cost:-15,approval:-5,economy:-1}];
function random(s){s.seed=(s.seed*1664525+1013904223)>>>0;return s.seed/4294967296}
function create(c){return {...c,version:1,seed:Date.now()>>>0,phase:'campaign',round:1,quarter:0,term:1,approval:42,support:32,local:45,economy:60,treasury:100,actions:3,seatsWon:0,rivalSeats:0,otherSeats:0,history:[],log:['Your political career begins. Build national support and earn your constituency’s trust.'],event:null,tab:'overview',enacted:[]}}
function act(s,type){if(!s.actions||s.event)return false;const table=s.phase==='campaign'?{rally:[4,1,-6],door:[2,6,-3],debate:[5,0,-4],fundraise:[-1,0,12],manifesto:[3,2,-5]}:{services:[2,3,-5],media:[2,0,-3],fundraise:[-1,0,8],scrutiny:[3,1,-2],organise:[2,3,-4]};const a=table[type];if(!a||s.treasury+a[2]<0)return false;s.actions--;s.treasury+=a[2];if(s.phase==='campaign')s.support=clamp(s.support+a[0]+(random(s)-.5)*3);else s.approval=clamp(s.approval+a[0]);s.local=clamp(s.local+a[1]);s.log.unshift('Completed '+type+'.');return true}
function election(s){const vote=clamp((s.phase==='campaign'?s.support:s.approval)+(random(s)-.5)*14,5,85);const fraction=1/(1+Math.exp(-(vote-46)/11));s.seatsWon=Math.round(s.seats*fraction);s.otherSeats=Math.round((s.seats-s.seatsWon)*.18);s.rivalSeats=s.seats-s.seatsWon-s.otherSeats;const won=s.system==='presidential'?vote>50:s.seatsWon>Math.floor(s.seats/2);s.phase=won?'government':'opposition';s.approval=clamp(vote+(won?7:2));s.quarter=0;s.actions=3;s.term++;s.enacted=[];s.history.push({year:s.year,vote:Math.round(vote),seats:s.seatsWon,won});s.log.unshift((won?'ELECTION WON. ':'ELECTION LOST. ')+Math.round(vote)+'% vote; '+s.seatsWon+' seats. '+(won?'You take office as '+s.office+'.':'You continue as Leader of the Opposition.'));return won}
function advance(s){if(s.event)return false;if(s.phase==='campaign'){s.round++;if(s.round>4){election(s);return true}s.treasury+=5;s.actions=3;s.log.unshift('Campaign week '+s.round+' begins.');return true}s.quarter++;s.year+=.25;s.treasury=clamp(s.treasury+10+(s.economy-50)/8,0,250);s.economy=clamp(s.economy+(random(s)-.5)*7);s.approval=clamp(s.approval+(s.economy-60)/12-1);s.actions=3;if(s.quarter>=s.termYears*4){election(s);return true}const events=[{title:'Cost of living pressure',text:'Households demand relief as prices climb.',choices:[['Targeted relief',-10,5,0],['Hold the budget line',5,-4,1],['Negotiate wage support',-5,2,2]]},{title:'Flood emergency',text:'Severe flooding has damaged communities and infrastructure.',choices:[['Fund immediate recovery',-13,6,1],['Seek private contributions',-4,1,0],['Delay the spending package',0,-7,-3]]},{title:'An ethics investigation',text:'A senior political ally faces questions over undisclosed donations.',choices:[['Demand an independent inquiry',-3,4,0],['Defend your ally',0,-6,0],['Publish all party donations',-5,5,0]]},{title:'Investment opportunity',text:'A manufacturer proposes a major new employment centre.',choices:[['Offer an investment grant',-10,2,5],['Fast-track with safeguards',-4,2,3],['Reject the proposal',0,-2,-2]]}];s.event=events[Math.floor(random(s)*events.length)];s.log.unshift('Quarter '+s.quarter+' of term: a new national issue demands a response.');return true}
function resolve(s,i){if(!s.event||!s.event.choices[i])return false;const c=s.event.choices[i];if(s.treasury+c[1]<0)return false;const opposition=s.phase==='opposition';s.treasury+=opposition?Math.min(0,c[1]/3):c[1];s.approval=clamp(s.approval+c[2]);if(!opposition)s.economy=clamp(s.economy+c[3]);s.log.unshift((opposition?'Opposition position: ':'Decision: ')+c[0]);s.event=null;return true}
function legislate(s,i){const p=policies[i];if(s.phase!=='government'||!s.actions||s.event||!p||s.enacted.includes(i)||s.treasury<p.cost)return false;s.actions--;s.treasury-=p.cost;const pass=s.system==='presidential'?random(s)<clamp(s.seatsWon/s.seats*100+15)/100:s.seatsWon>s.seats/2;if(pass){s.approval=clamp(s.approval+p.approval);s.economy=clamp(s.economy+p.economy);s.enacted.push(i)}else{s.treasury+=p.cost;s.approval=clamp(s.approval-2)}s.log.unshift(p.name+': '+(pass?'legislation passed.':'blocked by parliament.'));return true}
const api={create,act,election,advance,resolve,legislate,policies,clamp};if(typeof module!=='undefined')module.exports=api;root.Engine=api;
})(typeof globalThis!=='undefined'?globalThis:this);
