const assert=require('node:assert/strict'),E=require('./engine.js'),D=require('./data/politics.json');let checks=0;
function test(name,fn){fn();checks++;console.log('PASS',name)}
const profile=c=>D.countries[c]||D.regions.find(p=>p.code===c);
test('Country coverage and source references',()=>{assert.equal(Object.keys(D.countries).length,197);assert.equal(D.regions.length,67);const ids=new Set(D.sources.map(x=>x.id));for(const p of [...Object.values(D.countries),...D.regions]){assert(p.sources.every(x=>ids.has(x)));assert(new Set(p.districts.map(d=>d.name)).size===p.districts.length,p.code+' duplicate district names');assert(p.parties.every(x=>/^#[0-9a-f]{6}$/i.test(x.colour)));assert(p.seats>=0)}});
test('Official district counts and Electoral College allocation',()=>{for(const [c,n] of [['AU',150],['GB',650],['CA',343],['NZ',71],['DE',299],['US',435],['AU-NSW',93],['AU-VIC',88],['AU-QLD',93],['AU-WA',59],['AU-SA',47],['AU-NT',25],['GB-SCT',73],['GB-WLS',16],['CA-BC',93]])assert.equal(profile(c).districts.length,n,c);assert.equal(profile('US').presidentialStates.reduce((a,d)=>a+d.electors,0),538);assert.equal(profile('GB-WLS').seats,96);assert.equal(profile('IN').seats,543);assert.equal(profile('JP').constituencySeats,289)});
test('Current rosters and dated baselines',()=>{assert.equal(profile('AU').parties.filter(x=>x.name!=='Independent').length,33);assert.equal(profile('NZ').parties.length,17);assert.equal(profile('BR').parties.length,30);assert.equal(profile('CA').parties.length,16);assert.equal(profile('GB').parties.find(x=>x.name==='Labour').seats,403);assert.equal(profile('AU').parties.find(x=>x.name==='Australian Labor Party (ALP)').seats,94);assert.equal(profile('ZA').parties.reduce((a,p)=>a+p.seats,0),400);assert.equal(profile('US-NH').term,2);assert.equal(profile('US-VT').term,2);assert.equal(profile('US-VA').consecutiveLimit,1);assert.equal(profile('US-AK').mode,'governor-av')});
test('D’Hondt and Sainte-Laguë conserve seats',()=>{for(const m of ['dhondt','sainte']){const a=E.allocate([40,35,20,5],150,m);assert.equal(a.reduce((x,y)=>x+y),150);assert(a[0]>a[1]);assert(a[3]>0)}});
test('STV fills multi-member districts from generated ballots',()=>{const s={seed:12};const a=E.stv([44,32,16,8],7,s);assert.equal(a.reduce((x,y)=>x+y),7);assert(a[0]>0&&a[1]>0)});
test('Every profile runs and conserves its model seat total',()=>{for(const p of [...Object.values(D.countries),...D.regions]){const s=E.create(p,{party:p.parties[0]?.name,seed:123});const r=E.election(s,p);assert(r.counts.every(Number.isInteger),p.code);assert.equal(r.total,r.counts.reduce((a,x)=>a+x,0));assert(r.total>0,p.code);if(p.mode==='mmp-nz')assert(r.total>=s.seats);else assert.equal(r.total,s.seats,p.code);assert(Math.abs(s.poll.reduce((a,x)=>a+x,0)-100)<1e-7,p.code);assert(E.validSave(s,D),p.code)}});
test('Campaign advances eight weeks before election',()=>{const p=profile('AU'),s=E.create(p,{party:p.parties[0].name,seed:23});for(let i=0;i<7;i++){E.advance(s,p);assert.equal(s.phase,'campaign')}E.advance(s,p);assert(s.results);assert.equal(s.termNumber,1)});
test('Government term takes exactly 12 quarters in Australia',()=>{const p=profile('AU'),s=E.create(p,{seed:44,party:p.parties[0].name});s.poll=s.parties.map((_,i)=>i===s.player?95:5/(s.parties.length-1));E.election(s,p);assert.equal(s.phase,'government');const start=s.year;for(let i=1;i<=12;i++){E.advance(s,p);if(s.event)assert(E.resolve(s,1));if(i<12)assert.equal(s.phase,'government')}assert.equal(s.phase,'campaign');assert.equal(s.year,start+3)});
test('Opposition advocacy cannot spend public budget or change economy',()=>{const p=profile('AU'),s=E.create(p,{seed:54,party:'Australian Greens'});s.poll=s.parties.map((_,i)=>i===s.player?.1:99.9/(s.parties.length-1));E.election(s,p);if(s.phase==='negotiation')E.opposition(s);assert.equal(s.phase,'opposition');assert.equal(E.legislate(s,'health'),false);const before=s.budget,econ=s.economy;assert(E.propose(s,'health'));assert.equal(s.budget,before);assert.equal(s.economy,econ);s.event={choices:[{name:'Advocate aid',budget:-10,approval:3,economy:4,trust:1}]};assert(E.resolve(s,0));assert.equal(s.budget,before);assert.equal(s.economy,econ)});
test('Coalition formation requires sufficient supporting seats',()=>{const p=profile('NZ'),s=E.create(p,{seed:77,party:p.parties[1].name});E.election(s,p);s.phase='negotiation';s.coalition=[s.player];s.trust=100;let attempts=0;for(let i=0;i<s.parties.length&&s.phase==='negotiation';i++)if(i!==s.player&&s.results.counts[i])for(let j=0;j<20&&s.phase==='negotiation'&&!s.coalition.includes(i);j++){E.coalition(s,i);attempts++}assert.equal(s.phase,'government');assert(s.coalition.reduce((a,i)=>a+s.results.counts[i],0)>=s.results.majority)});
test('US Electoral College stays at 538 over different seeds',()=>{for(let seed=1;seed<15;seed++){const p=profile('US'),s=E.create(p,{seed,party:'Democratic Party'}),r=E.election(s,p);assert.equal(r.electors.reduce((a,x)=>a+x),538);assert.equal(r.rows.find(x=>x.region==='ME').electors.reduce((a,x)=>a+x),4);assert.equal(r.rows.find(x=>x.region==='NE').electors.reduce((a,x)=>a+x),5);assert.equal(s.termYears,4)}});
test('Starting a new party works in a limited profile',()=>{const p=profile('VA'),s=E.create(p,{seed:100,customParty:{name:'Civic Dawn',short:'CD',colour:'#765daa'},party:'Civic Dawn',sandboxSeats:100,sandboxTerm:4});assert(s.parties[s.player].custom);assert(s.scenario);assert.equal(s.seats,100);E.election(s,p);assert.equal(s.results.total,100)});
test('Save validation rejects unsupported state',()=>{const s=E.create(profile('AU'),{seed:2});assert(E.validSave(JSON.parse(JSON.stringify(s)),D));assert(!E.validSave({...s,version:1},D));assert(!E.validSave({...s,poll:[NaN]},D));assert(!E.validSave({...s,profile:'NOT-A-COUNTRY'},D))});
console.log(`${checks} test groups passed.`);
